### PR TITLE
Fix/finalize cypress

### LINKED ISSUE #42: Finalize Cypress testing
- Make sure any new features are tested
- Make sure all tests are passing
- Change name of file (currently Homepage but it has tests for everything so it's a little confusing as it is right now)

### LINKED ISSUE #47: Stub video API & test rendering in Cypress

### PR DESCRIPTION
**Pull request by tashiad**
## *Purpose:*
*What does this merge do? Check all that apply.*
- [x] Adds a new feature
- [x] Improves an existing feature
- [x] Fixes a bug
- [x] Cleans up (logs, tests, etc.)

## *Description: What does this PR do?*
* Created tests for added features (search/filtering and trailer rendering)
* Updated expected h1 and error message text in tests

## *Instructions for reviewer:*
*Where should the reviewer start?* `Tomatillos_spec.js`
*How should this be manually tested?* Running Cypress and checking that all tests pass
*Any background context you want to provide?* N/A
*What are the relevant tickets?*
Closes #42 
Closes #47 

## *Issues:*
"Should be able to search by movie title" seems to not pass occasionally and I'm not sure why...

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have used tests to prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my change

### CODE REVIEW

File: cypress/integration/Tomatillos_spec.js [hunk 1]
```diff
@@ -36,10 +36,12 @@ describe('Homepage', () => {
...
   })
 
-  it.skip('Should be able to filter by minimum movie rating', () => {
+  it('Should be able to filter by minimum movie rating', () => {
     cy
       .visit('http://localhost:3000')
-      .get('header').contains('h1', 'GrossVeggies')
+      .get('.input-field').type('6')
+      .get('.search-button').click()
+      .get('.poster').should('not.contain', 'Mulan')
```
Comment (Max9545) [inline cypress/integration/Tomatillos_spec.js:45]: Dinseybad!

File: cypress/integration/Tomatillos_spec.js [hunk 2]
```diff
@@ -2,7 +2,7 @@ describe('Homepage', () => {
   it('Should have correct header and subheader', () => {
     cy
       .visit('http://localhost:3000')
-      .get('header').contains('h1', 'RancidTomatillos')
+      .get('header').contains('h1', 'GrossVeggies')
```
Comment (Max9545) [inline cypress/integration/Tomatillos_spec.js:5]: @TM
